---
title: "Final project"
author: "Shubham and sanath"
date: "2023-04-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) # For data manipulation and visualization
library(lubridate) # For working with date-time data
library("ggplot2")
library(plotly)
library(leaflet)
library(leaflet.extras)

```

```{r}
# Load data
data <- read.csv("DataCoSupplyChainDataset.csv")
data_description <- read.csv("DescriptionDataCoSupplyChain.csv")

```

```{r}
# Display summary statistics for numerical variables
summary(data[, c("Days.for.shipping..real.","Days.for.shipment..scheduled.","Benefit.per.order","Sales.per.customer")])

```

```{r}
# Create a histogram of sales per customer
ggplot(data, aes(x = `Sales.per.customer`)) +
  geom_histogram() +
  labs(x = "Sales per customer", y = "Count", title = "Distribution of Sales per Customer")

```

```{r}
# Create a bar chart of delivery status
ggplot(data, aes(x = `Delivery.Status`)) +
  geom_bar() +
  labs(x = "Delivery Status", y = "Count", title = "Delivery Status Distribution")

```

```{r}
ggplot(data, aes(x = Late_delivery_risk, fill = Delivery.Status)) +
  geom_density(alpha = 0.5) +
  labs(title = "Late Delivery Risk by Delivery Status")

```
```{r}
ggplot(data, aes(x = Category.Name, y = Sales, fill = Category.Name)) +
  geom_boxplot() +
  labs(title = "Category Name vs. Sales")

```

```{r}

ggplot(data, aes(x = Shipping.Mode, y = Late_delivery_risk, fill = Shipping.Mode)) +
  geom_boxplot() +
  labs(title = "Shipping Mode vs. Late Delivery Risk")
```

```{r}
# Highest revenue based on Department.

sales_by_deapartmnet  <- aggregate(data$Sales, by = list(Department = data$Department.Name), FUN = sum)

# create the plot
d <- ggplot(sales_by_deapartmnet, aes(x = Department, y = x, fill = Department, text = paste("Department: ", Department, "<br>", "Sales: $", x))) +
  geom_bar(stat = "identity") +
  labs(title = "Total Sales by Department") +
  xlab("Department") +
  ylab("Sales") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# convert the plot to plotly
ggplotly(d)
```

```{r}

#Top 10 countries which are selling porduct to the customers.

# calculate the count of orders by Order.Country
orders_by_country <- data %>%
  group_by(Order.Country) %>%
  summarize(count = n()) %>%
  arrange(desc(count)) %>%
  slice(1:10)


#Error in the output Because of mexico
# create the plot 
p <- ggplot(orders_by_country, aes(x = Order.Country, y = count, fill = Order.Country, text = paste("Country: ", Order.Country, "<br>", "Orders: ", count))) +
  geom_bar(stat = "identity") +
  labs(title = "Top 10 Order Countries by Customer Orders") +
  xlab("Order Country") +
  ylab("Customer Orders") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


# convert the plot to plotly
ggplotly(p)


```

```{r}
#Plotting the region based sales to the customers.

# create a data frame with the count of orders by order region
order_region_count <- data %>%
  group_by(Order.Region) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) 

# create the plot
plot <- ggplot(order_region_count, aes(x = Order.Region, y = Count, fill = Order.Region, text = paste("Order Region: ", Order.Region, "<br>", "Order Count: ", Count))) +
  geom_bar(stat = "identity") +
  labs(title = "Order Regions by Count of Orders from Customers") +
  xlab("Order Region") +
  ylab("Order Count") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_fill_viridis_d()

# convert the plot to plotly
ggplotly(plot)

```

```{r}
# get the top 20 customers who did the highest sales.

# create a data frame with sales per customer
sales_per_customer <- data %>%
  group_by(Customer.Id) %>%
  summarise(total_sales = sum(Sales)) %>%
  arrange(desc(total_sales))

# get the top 20 customers who did the highest sales.

top_customers <- head(sales_per_customer, 20)

# create a new column with the combined first and last name of each customer
#Issue with row-1.
top_customers <- top_customers %>%
  left_join(data %>% select(Customer.Id, Customer.Fname, Customer.Lname), by = "Customer.Id") %>%
  mutate(CustomerName = paste(Customer.Fname, Customer.Lname, sep = " "))


# create the plot
plot <- ggplot(top_customers, aes(x = reorder(CustomerName, -total_sales), y = total_sales, fill = CustomerName, text = paste("Customer Name: ", CustomerName, "<br>", "Total Sales: $", total_sales))) +
  geom_bar(stat = "identity") +
  labs(title = "Top 20 Customers by Sales") +
  xlab("Customer Name") +
  ylab("Total Sales") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# convert the plot to plotly
ggplotly(plot)

```

```{r}
# Aggregate the data by Customer.City and calculate the total number of orders
Customer.City_orders <- data %>%
  group_by(Customer.City, Latitude, Longitude) %>%
  summarise(total_orders = n()) %>%
  arrange(desc(total_orders))

# Create color palette
colorPalette <- colorNumeric(palette = "YlOrRd", domain = Customer.City_orders$total_orders)

# Create heat map
# Set the initial view to focus on the US
m <- leaflet(Customer.City_orders) %>%
  addTiles() %>%
  setView(lng = -95.7129, lat = 37.0902, zoom = 4) %>%
  addHeatmap(lng = ~Longitude, lat = ~Latitude, intensity = ~total_orders, blur = 20, max = max(Customer.City_orders$total_orders))

m



```

